# https://github.com/rust-lang/cargo/issues/2078

[package]
name = "born_attribute"
version = "0.1.0"
authors = ["steadylearner <32325099+steadylearner@users.noreply.github.com>"]
edition = "2018"

[dependencies]
proc_macro_roids = "0.7.0"
quote = "1.0.6"
syn = "1.0.24"

[lib]
proc-macro = true


